easy_admin:
    site_name: 'Przychodnia'
    formats:
        datetime: 'd/m/Y H:i'

    design:
        menu:
            - {entity: 'Patient', icon: 'user'}
            - {entity: 'Doctor', icon: 'user-nurse'}
            - {entity: 'Visit', icon: 'calendar'}
            - {entity: 'Specjalization'}

    entities:
        Doctor:
            label: 'Lekarze'
            class:  App\Entity\Doctor
            search:
                fields: ['firstName', 'lastName', 'Specjalization.name']
            show:
                fields: ['firstName', 'lastName', 'Specjalization',
                         {label: 'Wizyta', property: 'visits', template: 'admin/visits.html.twig'}]

        Visit:
            label: 'Wizyta'
            class:  App\Entity\Visit


        Specjalization:
            label: 'Specjalizacja'
            class: App\Entity\Specjalization

        Patient:
            label: 'Pacjeci'
            class: App\Entity\Patient
            show:
                fields:
                    - {label: 'Imie', property: 'firstName'}
                    - {label: 'Nazwisko', property: 'lastName'}
            edit:
                fields:
                    - {label: 'Imie', property: 'firstName'}
                    - {label: 'Nazwisko', property: 'lastName'}
            list:
                fields:
                    - {label: 'ID', property: 'id'}
                    - {label: 'Imie', property: 'firstName'}
                    - {label: 'Nazwisko', property: 'lastName'}


    list:
        actions: ['show']


